### ISSUE TITLE
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method

### ISSUE THREAD

**Issue by myxor** [myxor/ha-bitstampnet#1]
Since last home-assistant version this error is thrown on startup:

`2020-03-07 20:46:45 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
`

**Comment by myxor** [comment]
Seems to be fixed by home-assistant update.
